services:
  db:
    image: mysql:lts
    container_name: edb-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'edb-root-pwd'
      MYSQL_USER: 'edb'
      MYSQL_PASSSWORD: 'edb-password'
      MYSQL_DATABASE: 'edb'
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - edb-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    container_name: edb-adminer
    restart: unless-stopped
    ports:
      - 127.0.0.1:8001:8080

volumes:
  edb-db:
