# Generated by Django 6.1 on 2026-08-23 10:56

import django.core.validators
import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion', models.DurationField()),
                ('estado', django_enum.fields.EnumCharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('APLAZADA', 'Aplazada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, max_length=640, null=True)),
                ('esta_habilitado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido', regex='^(\\+?\\d{1,3}-)?\\d{3}-\\d{3}-\\d{4}$')])),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('esta_habilitado', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=120, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Ingrese un precio igual o mayor que cero')])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('esta_habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(blank=True, max_length=40, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido', regex='^(\\+?\\d{1,3}-)?\\d{3}-\\d{3}-\\d{4}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', django_enum.fields.EnumCharField(choices=[('INSCRIPCION', 'Inscripción'), ('MENSUALIDAD', 'Mensualidad'), ('CLASE_INDIVIDUAL', 'Clase individual'), ('PAQUETE_CLASES', 'Paquete de clases')], max_length=16)),
                ('concepto', models.CharField(max_length=120, unique=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Ingrese un precio igual o mayor que cero')])),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('esta_habilitado', models.BooleanField(default=True)),
                ('clases', models.ManyToManyField(to='core.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(blank=True, max_length=40, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido', regex='^(\\+?\\d{1,3}-)?\\d{3}-\\d{3}-\\d{4}$')])),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('genero', django_enum.fields.EnumCharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('NO_BINARIO', 'No binario')], max_length=10, null=True)),
                ('estado_inscripcion', django_enum.fields.EnumCharField(choices=[('ACTIVO', 'Activo'), ('PAGO_PENDIENTE', 'Pago pendiente'), ('BAJA', 'Baja')], default='ACTIVO', max_length=14)),
                ('posee_tarjeta_asistencia', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('genero__in', ['HOMBRE', 'MUJER', 'NO_BINARIO']), ('genero__isnull', True), _connector='OR'), name='core_Estudiante_genero_Genero'), models.CheckConstraint(condition=models.Q(('estado_inscripcion__in', ['ACTIVO', 'PAGO_PENDIENTE', 'BAJA'])), name='core_Estudiante_estado_inscripcion_Estado')],
            },
        ),
        migrations.CreateModel(
            name='ClaseEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(through='core.ClaseEstudiante', to='core.estudiante'),
        ),
        migrations.AddField(
            model_name='clase',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.instructor'),
        ),
        migrations.CreateModel(
            name='PagoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', django_enum.fields.EnumCharField(choices=[('PENDIENTE', 'Pendiente'), ('POR_CONFIRMAR', 'Por confirmar'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=13)),
                ('cuotas', models.ManyToManyField(to='core.cuota')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_finalizacion', models.DateTimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.curso')),
            ],
        ),
        migrations.AddField(
            model_name='cuota',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodo'),
        ),
        migrations.AddField(
            model_name='clase',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.periodo'),
        ),
        migrations.CreateModel(
            name='PagoInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('esta_confirmado', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.instructor')),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.salario')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='salario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.salario'),
        ),
        migrations.CreateModel(
            name='TutorEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', django_enum.fields.EnumCharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HERMANO', 'Hermano/a'), ('TIO', 'Tío/a'), ('ABUELO', 'Abuelo/a'), ('TUTOR_LEGAL', 'Tutor legal')], max_length=11)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='estudiantes',
            field=models.ManyToManyField(through='core.TutorEstudiante', to='core.estudiante'),
        ),
        migrations.AddConstraint(
            model_name='claseestudiante',
            constraint=models.UniqueConstraint(fields=('clase', 'estudiante'), name='unique_clase_estudiante'),
        ),
        migrations.AddConstraint(
            model_name='pagoestudiante',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'POR_CONFIRMAR', 'COMPLETADO', 'CANCELADO', 'DEVUELTO'])), name='core_PagoEstudiante_estado_Estado'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['INSCRIPCION', 'MENSUALIDAD', 'CLASE_INDIVIDUAL', 'PAQUETE_CLASES'])), name='core_Cuota_tipo_Tipo'),
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'EN_CURSO', 'APLAZADA', 'COMPLETADA'])), name='core_Clase_estado_Estado'),
        ),
        migrations.AddConstraint(
            model_name='tutorestudiante',
            constraint=models.UniqueConstraint(fields=('tutor', 'estudiante'), name='unique_tutor_estudiante'),
        ),
        migrations.AddConstraint(
            model_name='tutorestudiante',
            constraint=models.CheckConstraint(condition=models.Q(('parentesco__in', ['PADRE', 'MADRE', 'HERMANO', 'TIO', 'ABUELO', 'TUTOR_LEGAL'])), name='core_TutorEstudiante_parentesco_Parentesco'),
        ),
    ]
