# Generated by Django 6.1 on 2026-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_finalizacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
