# Generated by Django 6.1 on 2026-08-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
