# Generated by Django 6.1 on 2026-08-24 04:58

import core.utils
import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_periodo_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=core.utils.generate_uuid_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'odt', 'txt', 'pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_file_size])),
                ('notas', models.TextField(blank=True, max_length=120, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pagoestudiante')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.tipodocumento')),
            ],
        ),
    ]
