# Generated by Django 6.1 on 2026-08-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clase_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='clases', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='clases',
            field=models.ManyToManyField(blank=True, null=True, related_name='cuotas', to='core.clase'),
        ),
    ]
