# Generated by Django 6.1 on 2026-08-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instructor'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pagoestudiante'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.tipodocumento'),
        ),
    ]
