# Generated by Django 6.1 on 2026-08-24 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clase_estudiantes_alter_cuota_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='clases', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='clases',
            field=models.ManyToManyField(blank=True, related_name='cuotas', to='core.clase'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.periodo'),
        ),
    ]
