# Generated by Django 6.1 on 2026-08-25 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clase_estudiantes_alter_cuota_clases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.periodo'),
        ),
    ]
