# Generated by Django 6.1 on 2026-08-25 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cuota_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaPagada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pagoestudiante')),
            ],
        ),
    ]
