# Generated by Django 6.1 on 2026-08-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(related_name='clases', through='core.ClaseEstudiante', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clases', to='core.instructor'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clases', to='core.periodo'),
        ),
        migrations.AlterField(
            model_name='claseestudiante',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_clase', to='core.clase'),
        ),
        migrations.AlterField(
            model_name='claseestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clases_estudiante', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='clases',
            field=models.ManyToManyField(related_name='cuotas', to='core.clase'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.periodo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.instructor'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.pagoestudiante'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='core.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='salario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='instructores', to='core.salario'),
        ),
        migrations.AlterField(
            model_name='pagoestudiante',
            name='cuotas',
            field=models.ManyToManyField(related_name='pagos_estudiantes', to='core.cuota'),
        ),
        migrations.AlterField(
            model_name='pagoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='pagoinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='core.instructor'),
        ),
        migrations.AlterField(
            model_name='pagoinstructor',
            name='salario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='instructores_salario', to='core.salario'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='periodos', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='estudiantes',
            field=models.ManyToManyField(related_name='tutores', through='core.TutorEstudiante', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='tutorestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tutores_estudiante', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='tutorestudiante',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estudiantes_tutor', to='core.tutor'),
        ),
    ]
