# Generated by Django 6.1 on 2026-08-25 02:24

from django.db import migrations

def migrate_fees(apps, schema_editor):
    PagoEstudiante = apps.get_model('core', 'PagoEstudiante')
    CuotaPagada = apps.get_model('core', 'CuotaPagada')

    for payment in PagoEstudiante.objects.all():
        for fee in payment.cuotas.all():
            CuotaPagada.objects.create(
                pago=payment,
                cuota=fee,
                monto=fee.costo,
            )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cuotapagada'),
    ]

    operations = [
        migrations.RunPython(migrate_fees)
    ]
