# Generated by Django 6.1 on 2026-08-25 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20260825_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoestudiante',
            name='cuotas',
        ),
    ]
