# Generated by Django 6.1 on 2026-08-25 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_pagoestudiante_cuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoestudiante',
            name='cuotas',
            field=models.ManyToManyField(related_name='pagos_estudiantes', through='core.CuotaPagada', to='core.cuota'),
        ),
        migrations.AlterField(
            model_name='cuotapagada',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos_cuota', to='core.cuota'),
        ),
        migrations.AlterField(
            model_name='cuotapagada',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_pago', to='core.pagoestudiante'),
        ),
    ]
