# Generated by Django 6.1 on 2026-08-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pagoestudiante_cuotas_alter_cuotapagada_cuota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotapagada',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pagoestudiante',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddConstraint(
            model_name='cuotapagada',
            constraint=models.UniqueConstraint(fields=('cuota', 'pago'), name='unique_cuota_pago'),
        ),
    ]
