# Generated by Django 6.1 on 2026-08-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cuotapagada_monto_alter_pagoestudiante_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('asistio', models.BooleanField(default=False)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.estudiante')),
            ],
        ),
    ]
