# Generated by Django 6.1 on 2026-08-25 05:12

from django.db import migrations

def migrate_students(apps, schema_editor):
    Clase = apps.get_model('core', 'Clase')
    ClaseEstudiante = apps.get_model('core', 'ClaseEstudiante')

    for theClass in Clase.objects.all():
        for student in theClass.estudiantes.all():
            ClaseEstudiante.objects.create(
                clase=theClass,
                estudiante=student
            )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_claseestudiante'),
    ]

    operations = [
        migrations.RunPython(migrate_students)
    ]
