# Generated by Django 6.1 on 2026-08-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20260825_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='estudiantes',
        ),
    ]
