# Generated by Django 6.1 on 2026-08-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_clase_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(related_name='clases', through='core.ClaseEstudiante', to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='claseestudiante',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_clase', to='core.clase'),
        ),
        migrations.AlterField(
            model_name='claseestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clases_estudiante', to='core.estudiante'),
        ),
        migrations.AddConstraint(
            model_name='claseestudiante',
            constraint=models.UniqueConstraint(fields=('clase', 'estudiante'), name='unique_clase_estudiante'),
        ),
    ]
