# Generated by Django 6.1 on 2026-08-26 03:57

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clase_estudiantes_alter_claseestudiante_clase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[core.validators.validate_year]),
        ),
        migrations.AddField(
            model_name='cuota',
            name='cantidad_clases',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='mes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[core.validators.validate_month]),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='contador_clases_restantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Ingrese un monto igual o mayor que cero')]),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono en formato 000-000-000', regex='^(\\+?\\d{1,3}-)?\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telefono',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono en formato 000-000-000', regex='^(\\+?\\d{1,3}-)?\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='salario',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Ingrese un monto igual o mayor que cero')]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono en formato 000-000-000', regex='^(\\+?\\d{1,3}-)?\\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
