# Generated by Django 6.1 on 2026-08-26 20:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cuota_anio_cuota_cantidad_clases_cuota_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clases', to='core.curso'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono en formato 000-000-000 o +00-000-000-000', regex='^(\\+?\\d{1,3}-)?\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telefono',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono en formato 000-000-000 o +00-000-000-000', regex='^(\\+?\\d{1,3}-)?\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono en formato 000-000-000 o +00-000-000-000', regex='^(\\+?\\d{1,3}-)?\\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
