# Generated by Django 6.1 on 2026-08-26 20:51

from django.db import migrations

def migrate_courses(apps, schema_editor):
    Cuota = apps.get_model('core', 'Cuota')
    Clase = apps.get_model('core', 'Clase')

    for theClass in Clase.objects.all():
        print(theClass)
        theClass.curso = theClass.periodo.curso
        theClass.save(update_fields=['curso'])

    for fee in Cuota.objects.filter(periodo__isnull=False):
        fee.curso = fee.periodo.curso
        fee.save(update_fields=['curso'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clase_curso_cuota_curso_alter_estudiante_telefono_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_courses)
    ]
