# Generated by Django 6.1 on 2026-08-26 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20260826_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clases', to='core.curso'),
        ),
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
