# Generated by Django 6.1 on 2026-08-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_cuota_periodo_remove_clase_periodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='clases',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='mes',
        ),
    ]
