# Generated by Django 6.1 on 2026-08-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_cuota_anio_remove_cuota_clases_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagoestudiante',
            old_name='total',
            new_name='monto',
        ),
        migrations.AddField(
            model_name='pagoestudiante',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='core.cuota'),
        ),
    ]
