# Generated by Django 6.1 on 2026-08-27 08:56

from django.db import migrations

def migrate_payments(apps, schema_editor):
    PagoEstudiante = apps.get_model('core', 'PagoEstudiante')

    for payment in PagoEstudiante.objects.all():
        related_fees = payment.cuotas_pago.all()
        quantity = related_fees.count()

        if quantity == 0:
            payment.delete()
            continue

        fee = related_fees.first()
        payment.cuota = fee.cuota
        payment.monto = fee.monto
        payment.save(update_fields=['cuota', 'monto'])

        for fee in related_fees[1:]:
            PagoEstudiante.objects.create(
                estudiante=payment.estudiante,
                fecha_registro=payment.fecha_registro,
                fecha_confirmacion=payment.fecha_confirmacion,
                estado=payment.estado,
                cuota=fee.cuota,
                monto=fee.monto,
            )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_total_pagoestudiante_monto_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_payments)
    ]
