# Generated by Django 6.1 on 2026-08-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20260827_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensualidadPagada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('fecha_vigencia', models.DateField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='cuotapagada',
            name='unique_cuota_pago',
        ),
        migrations.RemoveField(
            model_name='pagoestudiante',
            name='cuotas',
        ),
        migrations.AlterField(
            model_name='pagoestudiante',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='core.cuota'),
        ),
        migrations.AlterField(
            model_name='pagoestudiante',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddField(
            model_name='mensualidadpagada',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mensualidades', to='core.estudiante'),
        ),
        migrations.DeleteModel(
            name='CuotaPagada',
        ),
    ]
