# Generated by Django 6.1 on 2026-08-27 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mensualidadpagada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='mensualidadpagada',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='mensualidadpagada',
            name='pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='pago_estudiantes', to='core.pagoestudiante'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='mensualidadpagada',
            constraint=models.UniqueConstraint(fields=('estudiante', 'pago'), name='unique_estudiante_pago'),
        ),
    ]
