# Generated by Django 6.1 on 2026-08-28 08:48

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_cuota_fecha_limite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_max_ninio', models.PositiveSmallIntegerField(default=12)),
                ('edad_min_adulto', models.PositiveSmallIntegerField(default=18)),
                ('margen_antes_fin_vigencia', models.PositiveSmallIntegerField(default=10)),
                ('intervalo_comprobacion', models.PositiveIntegerField(default=24)),
                ('alertar_fin_mensualidad', models.BooleanField(default=True)),
                ('alertar_clases_agotadas', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, unique=True)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_ganancias', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_perdidas', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cantidad_transacciones', models.PositiveIntegerField(default=0)),
                ('cantidad_ventas', models.PositiveIntegerField(default=0)),
                ('cantidad_cancelaciones', models.PositiveIntegerField(default=0)),
                ('cantidad_devoluciones', models.PositiveIntegerField(default=0)),
                ('cantidad_salarios', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', django_enum.fields.EnumCharField(choices=[('MENSUALIDAD_VENCIDA', 'Mensualidad vencida'), ('MENSUALIDAD_PROXIMA', 'Mensualidad próxima a vencer'), ('CLASES_AGOTADAS', 'Sin clases restantes')], max_length=19)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, max_length=120, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.estudiante')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['MENSUALIDAD_VENCIDA', 'MENSUALIDAD_PROXIMA', 'CLASES_AGOTADAS'])), name='core_AlertaEstudiante_tipo_Tipo')],
            },
        ),
    ]
