# Generated by Django 6.1 on 2026-08-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_configuracion_registrodiario_alertaestudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrodiario',
            old_name='total_egresos',
            new_name='egreso_total',
        ),
        migrations.RenameField(
            model_name='registrodiario',
            old_name='total_ganancias',
            new_name='ganancia_total',
        ),
        migrations.RenameField(
            model_name='registrodiario',
            old_name='total_ingresos',
            new_name='ingreso_total',
        ),
        migrations.RenameField(
            model_name='registrodiario',
            old_name='total_perdidas',
            new_name='perdida_total',
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='ticket_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
