# Generated by Django 6.1 on 2026-08-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_total_egresos_registrodiario_egreso_total_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alertaestudiante',
            name='core_AlertaEstudiante_tipo_Tipo',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='alertar_clases_agotadas',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='alertar_fin_mensualidad',
        ),
        migrations.DeleteModel(
            name='AlertaEstudiante',
        ),
    ]
