# Generated by Django 6.1 on 2026-08-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_alertaestudiante_core_alertaestudiante_tipo_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='intervalo_comprobacion',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='modo_oscuro',
            field=models.BooleanField(default=False),
        ),
    ]
